spring:
  application:
    name: customer-service
  datasource:
    url: jdbc:postgresql://localhost:5432/customerdb # Replace with your database details
    username: "parisadb" # Replace with your database username
    password: "tiss&&161718" # Replace with your database password
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update # Automatically updates the schema
    show-sql: true     # Log SQL queries

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true

server:
  port: 8005

logging:
  level:
    org.springframework: DEBUG